appservice-discord: ENC[AES256_GCM,data:+NCDydkck4sXAludF3pTwWZQeQCc2GsmQVghSqUdwfZUDPYEvySi7uybiUIttZqQjOUKsGBQTO9YkMVQRQl5Yh1kseLzJg1+47k0pnzADXYAecz02M7F+diqOtOEsOcR5HZS4FkwdOJkfDzuQReqHRVEob1ZRYUIUhcUaNSDInF8das0V0O7SmwcCckpByrrtxsnAw==,iv:RmMqdTMKUAk29XKDO4FAh+HcMqYiqjsPPNLUD8xRcPM=,tag:Cj6T3JK4pp7vPPCh8HCthQ==,type:str]
sliding-sync: ENC[AES256_GCM,data:zxwCy9yD4mNAr4pry6zTxPQXl3XbROxak4ietNNdyfW1BDklcgBaem+Q7OGMQMpSNEIv5AGW+BoKx3v/nAmA2aFMYHvkzNmAbytk6xhD6A==,iv:6WIPyF6sgOn+TZaLcQX3j83LN2Kx9SIw1NhmySuj+sM=,tag:kBqGOEKgvZqsSvgozYi9ZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mwuzlgcvgvrfmw5qey3jjt0dmzm3tdfmpvu76t50l9srw0s5puvq2hqxl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU0VzakhQQ1lGLzQ1Qzd4
            UnhMa2Y3R1l4TktTVElKWGdBL3I0WWJ5V0E0CjBoTmJYV1VnM2ZNNWhIRFpUVkJL
            THJVbmFqYzIrZnVybUNsUS9PVDY5OFUKLS0tIHZtRWtpc0NnUlUrQndnK0MyRkRx
            cjF2QWgzMkwycTgwRnRSUzc1ZVk4MVEK0jfLpzykr0DSmUnj9SMzRvbehpIOCxvW
            Jg/824cKgifitky1IWWfOHkKEOZD5ofyWKr5CpAVzc5cp4IK9wQQIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yekmwz9jlrhuwxqsc28wxs4er3aeuua6g5kjn7qz0kqgagdsxegqysghxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK01TVWx1d05NWjVTU2pP
            cU1PdHBQZkJqd25kbDYwSVh5L1VhQmVpMVEwCnRmcTZucmV5WHA5M2wzUHBXVDA2
            OVFMTWFFVnU1MU1vRS9UclFPZ2RXWTAKLS0tIDM1MHZaMmRmKzQ2dWdaWFBYY2Zj
            SzZZZW05QStGZVZZNGsrZHBkUSttbDAKGivck6A57dPlrHY8FMfS43NBCe40ELE6
            Vc3w7XUqRglV5w15e5iBYwzOxeDi+q7/uJ0fVvJMzSeKIa57NydjfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-22T22:40:55Z"
    mac: ENC[AES256_GCM,data:vdsV46NEWrWcBCBPx4qfrs9jv14ePFAz9NjrrfFxxdUEK9iHfHxZI7lJbTp1q5KHqUdyduL5zgwnyRs92slRikSa/xLw6w909PhRm812tSbo8zhi0mluiswRYkSogoDecgs3fmDdd4zyBpK3oXvjx4AZQ1U1+S14l+UKHVN5m2g=,iv:Vi0Gqrq287ObBEgWHYfQC+GU8zEYRphbEDGm49fcX8g=,tag:Zt6df+3fNvMxFHNdYMGrXQ==,type:str]
    pgp:
        - created_at: "2022-11-15T20:40:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DnyFZoTOIVngSAQdAHoBGzI6+anBbZdBzSx9iZv0pv2omlIizThrkZYojY2Uw
            GlTFz7KwxHm6pkuBpcQqtKetx8OIzy+0MMK1oSU/+zM0WDHnkNLq2qkSkDSAS6Au
            0lgB5OuutPYMuI9uU5ooHpOvwV351GUoRxuUa8E3fs9uo5G0J1xOfDmEX5f1naKN
            CtfQufEz5RsVEs9vcUGUnEdE165b682y6G5qmhEewnourzf7v8b2csDH
            =akEc
            -----END PGP MESSAGE-----
          fp: 46CE7FF89C5B5C099224F63BDA4450E18B0B0C49
    unencrypted_suffix: _unencrypted
    version: 3.8.0
