hello: ENC[AES256_GCM,data:c8eRenDHSjG1MD97fEBJTfY7NOjeXv9n3r57h3ZeJaPhXucwUxVtYClzS+aaYg==,iv:IaYXgJTHGQlMy78sl8iZm5Vwj8peBEYXXLDqDNs3bVk=,tag:11IkWYS6Z3feGiyWflTTkA==,type:str]
example_key: ENC[AES256_GCM,data:e9ErsUMz7K+2IcXmiw==,iv:bMe4jTFUX3BtZB8/eh9bksUSkIOJqpX5qllUf/uT5CQ=,tag:9DioqRmvDzT64zuxHpFtGg==,type:str]
#ENC[AES256_GCM,data:QhHh2/SAk5SFzJpCAlVJcg==,iv:TkUKnb058foh7TR4WndF/wyLtg49NEUy//rzrva96BY=,tag:Vcbt+1RfLiHnPE22tvYdEA==,type:comment]
example_array:
    - ENC[AES256_GCM,data:WtKAw1L0HZZxXTVRJyA=,iv:9d34WSgYvpP6/hMXFqFqDvX/exXPUqzTb1LY0ljKdiY=,tag:wLSmr14gU0U28zPCrxPoww==,type:str]
    - ENC[AES256_GCM,data:aEwiiP1R19x7uDBh9Yk=,iv:ffL9AgS9DTqS+ezPuqyF5Z7vxN76EcxXypcfYxVH+/U=,tag:f9kk+pRBHbqmh5scuwmLPg==,type:str]
example_number: ENC[AES256_GCM,data:FIjouk7RilB2Yg==,iv:1htlkbmCzxyjpUF5dX0FtYMFW83tKNfNYUyVlUCz10c=,tag:CHrxMxHXl17bvYjvJcY25w==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:W/vx0A==,iv:z5Qk0gaJkkk8D2uxlR4IO9FGcTYkONDCxNTNCDIn2DE=,tag:p2UFjk/u41xnCEb7zuHdCw==,type:bool]
    - ENC[AES256_GCM,data:/aG8Djs=,iv:ZymV4TeruISwY0A3ZFF6GKcR8jdoF37BO/okHN3Kiz4=,tag:Q/IY7bVq2buIF+2yI5cn/w==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mwuzlgcvgvrfmw5qey3jjt0dmzm3tdfmpvu76t50l9srw0s5puvq2hqxl6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMDF2WDNFbE5rWEVZeGZH
            YUptWGtwaFMwc2prdm9pa3J1d2lnMVNDKzBvClc1akpDcU11TkpuQ3FONXAxOUdr
            WHNIU1pzUmRocFRTRmtFRjhwWUhncjAKLS0tIDJCREpzR1JxQjlINlB0UjFnK2Ux
            ajE0b3ArVnJhVWVEakVIMW9GeTVXRGMKZI7MRDYPBWaHVmhndsMyHsE0MNBxLbL5
            lpM24Ezd6PkMCeQZxnCr8AtETilAe8wH93KI7joUzvyXbXvelb0/Mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yekmwz9jlrhuwxqsc28wxs4er3aeuua6g5kjn7qz0kqgagdsxegqysghxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZGNGMzU0cTRtakVaTGRt
            RlhrTEd5WkZzTFBQQlIxSkl3QnArcTFEeHpBCkoyeHgzdGFSdEc2K1NZWm9vZmxw
            SC9oSzhPdmtQdm1aUEc4YXcwbVpQc2cKLS0tIERScHprQTNvdEF5M1ZNS3liNkdN
            TXl4QUFPSHE5WEY1ZDQrditjL2M3Z3MKevxUymd8oqawObAJgKONHcI86nqGE0rZ
            s8a27tF3WdJE5xYndtDsCF+5ouF+e7pR/V+oOm/ckdI1WUB6/pDAog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-15T20:16:29Z"
    mac: ENC[AES256_GCM,data:XMN+YOIFXLTtiDlvjOB18nAWNjTgx0OoN5JGczQkU1ZOOU+YCm9wfJ+9+urKJ0pgmXJH8Nf5KXBhDc8yWL5RWY8Xxaam0EqsTXIpOttFY/8kvPy6NoFr/LyxoZOcbwHClloamscQnp01zd8Fn+wZSv+A2R1Y7maC4TKhTohe41I=,iv:q7Jfs4c5qmzw9t913cvRDpdNKXy9YhUHnx0RzXQjij0=,tag:Ov4A4l1Ac6sHrpcyNlBnUQ==,type:str]
    pgp:
        - created_at: "2022-11-15T20:18:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DnyFZoTOIVngSAQdASyq5FyliPpJtVC9eYG1fM9H/udWHZktNSM6noFVX8R8w
            0j6bLo0VK+HlmXO37tCPXDYpTSTDx8j4/CyTrX9jYJUMIR/7vPKRFqh5VNe0ksx6
            0lgBPrwfxPaizkbnCIe2xG2NFbT6K608Ol5JAl8zRzKIKbEyFokMqUF+qd64SEC/
            FErZgxE3OtD6KbtfmUmMN6ySqP5n69h6ibPm5zafx8i7DpWN9tXGLRDi
            =r2En
            -----END PGP MESSAGE-----
          fp: 46CE7FF89C5B5C099224F63BDA4450E18B0B0C49
    unencrypted_suffix: _unencrypted
    version: 3.7.3
