name: Build NixOS configs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - hydra
          - bnas
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: Mic92/niks3-action@v1
        with:
          server-url: https://niks3.fu.io

      - name: Build ${{ matrix.config }}
        run: |
          nix build '.#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel'
